# Generated by Django 4.0.1 on 2022-01-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_postmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
