# Generated by Django 4.0.1 on 2022-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_postmodel_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equal_record',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lost_record',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='win_record',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
