# Generated by Django 4.0.1 on 2022-02-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_profile_equal_record_profile_lost_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='equal_record',
        ),
    ]
