# Generated by Django 4.0.1 on 2022-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_profile_equal_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='percent_record',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
